apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    serviceName: gw
  name: gw
spec:
  replicas: 1
  selector:
    matchLabels:
      serviceName: gw
  strategy: {}
  template:
    metadata:
      labels:
        serviceName: gw
    spec:
      containers:
        - env:
            - name: SMS_SERVICE_HOST
              value: sms-service.default.svc.cluster.local
          image: sms-gw:1.0.0
          name: sms-gateway
          resources: {}
          stdin: true
          imagePullPolicy: Never
      restartPolicy: Always

