apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    serviceName: svc
  name: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      serviceName: svc
  strategy: {}
  template:
    metadata:
      labels:
        serviceName: svc
    spec:
      containers:
        - env:
            - name: GW_URL
              value: test
          image: sms-svc:1.0.0
          name: sms-service
          resources: {}
          stdin: true
          imagePullPolicy: Never
      restartPolicy: Always
